Repository rdkcentral/rdk-halif-test-deepsleep_manager, pull requests merged in 2024-06, with the labels that each got.

#6 deepsleep: Adding MACRO ENABLE_ENHANCED_ERROR_CODE to enable/disable the enhanced
  profiles/deepsleepmanagerExtendedEnumsNotSupported.yaml
  src/test_l1_deepSleepMgr.c
Labels: bug

#4 Test Specification document for Deepsleep manager
  docs/pages/deep-sleep-manager_High-Level_TestSpec.md
  docs/pages/deep-sleep-manager_L2-Low-Level_TestSpec.md
  docs/pages/l2_module_test_specification_template.md
  src/test_l2_deepSleepMgr.c
Labels: documentation

#11 Feature/issue10 deepsleepmanager makefile update
  Makefile
  build.sh
Labels: L2 Work Element
