Repository rdkcentral/rdk-halif-test-deepsleep_manager, pull requests merged in 2025-03, with the labels that each got.

#29 gh #28 update hal_test binary
  Makefile
  README.md
  bin/run.sh
  host/install.sh
Labels: enhancement

#41 gh #40 removed the duplicate yaml and renamed in meaningful way
  host/tests/configs/deviceConfig.yml
  profiles/deepsleepmanagerWakeUpSources.yaml
  profiles/sinkWakeUpSources.yaml
Labels: bug

#39 gh #35 l1 l2 deep sleep manager python environment
  docs/pages/deep-sleep-manager_L1_L2_TestProcedure.md
  host/tests/L1_L2_TestCases/deepsleepmanager_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/deepsleepmanager_L1_L2_tests.py
  host/tests/deepsleepClasses/deepsleep.py
  host/tests/deepsleepClasses/deepsleep_testConfig.yml
  profiles/deepsleepmanagerWakeUpSources.yaml
  src/test_l1_deepSleepMgr.c
  src/test_l2_deepSleepMgr.c
Labels: documentation, enhancement

#44 gh #43: support for step result dump
  bin/deepsleepmanager/run.sh
  host/tests/L1_L2_TestCases/deepsleepmanager_L1_L2_tests.py
  host/tests/deepsleepClasses/deepsleep.py
Labels: bug, enhancement
